### ISSUE TITLE
Linux Compatibility (Ubuntu)

### ISSUE THREAD

**Issue by bauerem** [meemknight/cmakeSetup#4]
As I am learning and don't know any better, I prefer to use the terminal `cmake ../` and `make`.
To build this project I had to do install the following:
sudo apt-get install libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libgl1-mesa-dev

After that, I was able to `cmake ../` and `make` but when I tried to run the build `./mygame`, I got:
mygame: /home/user/cmakeSetup/thirdparty/glfw-3.3.2/src/input.c:832: glfwSetKeyCallback: Assertion `window != NULL' failed.
Aborted (core dumped)

Does this repo not work on Linux afterall, or is this another issue?

**Comment by meemknight** [comment]
Hm the repo should work on Linux, but I don't actively test it, message me on Discord so we can solve this

this is my discord community, I am Low Level Game Dev there
https://discord.gg/eehehsPAka
you can tag me there or message me in private
